# Generated by Django 5.0.7 on 2024-08-03 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_contacts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packages',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
