# Generated by Django 5.0.7 on 2024-08-04 12:18

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_alter_packages_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packages',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(default=1, verbose_name='Text'),
            preserve_default=False,
        ),
    ]
