# Generated by Django 5.0.7 on 2024-08-06 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_alter_packages_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('phone', models.CharField(max_length=25)),
                ('additional_info', models.TextField()),
                ('packages', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.packages')),
            ],
        ),
    ]
