# Generated by Django 5.0.7 on 2024-08-06 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0009_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='additional_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
