# Generated by Django 5.0.7 on 2024-08-15 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0010_alter_booking_additional_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages',
            name='slug',
            field=models.SlugField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
